### ISSUE TITLE
Stable support

### ISSUE THREAD

**Issue by Hoverbear** [lambda-fairy/maud#17]
I (@lambda-fairy) am adopting the top comment to summarize the unstable features used in Maud. The original text can be found at the bottom of this comment.

Summary of unstable features:

* **Mandatory**
    * `proc_macro_hygiene` (rust-lang/rust#54727)
* **Can be removed, but will make the library less nice to use**
    * `proc_macro_diagnostic` (rust-lang/rust#54140)
    * `proc_macro_span` (rust-lang/rust#54725)
* **Can be removed, but will make the library slower**
    * `specialization` (rust-lang/rust#31844)
* **Can be removed, but will make the implementation more complex**
    * `proc_macro_def_site` (rust-lang/rust#54724)
    * `proc_macro_quote` (rust-lang/rust#54722)

-----

*Original comment by Hoverbear:*

Hey! You might be able to get this to work on stable with [Syntex](https://github.com/erickt/rust-syntex).

**Comment by lfairy** [comment]
Good idea.

I'm too busy with other things at the moment, but I'll be happy to take a PR.

**Comment by TheNeikos** [comment]
This has been rendered not possible for now due to: https://github.com/lfairy/maud/blob/master/maud/src/lib.rs#L1

**Comment by Hoverbear** [comment]
Specialize is expected to land eventually so this should be possible again within the next 18 weeks. :)

**Comment by lfairy** [comment]
@Hoverbear do you have a source for that? According to rust-lang/rust#31844 there's still a soundness hole in the implementation, and I don't think they'd stabilize before that gets fixed.

**Comment by Hoverbear** [comment]
Ah yes you're right! Darn. :(

**Comment by lfairy** [comment]
We probably want to skip straight to rust-lang/rust#1566 when that's ready.

The library only uses specialization for optimizations, so it's harmless to remove that feature if need be. That might be useful if somehow procedural macros stabilize before specialization.

**Comment by dmwp37** [comment]
[proc-macro2](https://crates.io/crates/proc-macro2) may help to remove the `#![feature(proc_macro)]` feature dependency

**Comment by madmaxio** [comment]
Hey, this is still low priority thing?

**Comment by lfairy** [comment]
@madmaxio yes – nothing about the linked issues has changed since the last update.

**Comment by madmaxio** [comment]
You are talking about things @Hoverbear listed, right?

**Comment by lfairy** [comment]
Hoverbear didn't list them (read the comment carefully), but yes 🙂

**Comment by jhpratt** [comment]
Though far from ideal, proc macro back could be used to work around the "mandatory" feature gate.

**Comment by jhpratt** [comment]
With proc macro hygiene almost certainly landing on stable in 1.45, is there any change this might be considered again?

**Comment by madmaxio** [comment]
Proc macro thing go stable? Really?

**Comment by jhpratt** [comment]
Yup! It's in FCP now.

**Comment by lambda-fairy** [comment]
Thanks for the heads up @jhpratt! For some reason I wasn't subscribed to that tracking issue, so I almost missed it altogether.

I think the next step is to scope out what is to be done. It's not as simple as removing a `#![feature]` flag -- we have to decide what to do with the diagnostic messages, for example. I'm hoping to get a plan together by the end of the month.

**Comment by lambda-fairy** [comment]
As promised, I've written up some tasks: https://github.com/lambda-fairy/maud/milestone/1

Feel free to take any of them! (But please comment on the issue if you do, so that other people know you're working on it.)

That's not the complete list, but I think that's all that can be parallelized at this time. The remaining two items (translating errors to panics, migrating to `proc_macro2`) will involve much churn and may conflict with other work if done up front.

**Comment by lambda-fairy** [comment]
[0.22.1](https://crates.io/crates/maud/0.22.1) works on stable.
