### ISSUE TITLE
Pretty HTML output

### ISSUE THREAD

**Issue by KyleU** [lambda-fairy/maud#179]
Currently Maud outputs minified HTML, the smallest possible representation. Can it output multiline and indented (pretty) HTML? Love the project, it's been very useful

**Comment by lambda-fairy** [comment]
Thanks!

As mentioned in #164, I am hesitant to add that feature to Maud. There are already tools for formatting the HTML after-the-fact (e.g. HTML Tidy); it is also unclear what the API for formatting in the library would look like.

Do you have a specific use case in mind?

**Comment by KyleU** [comment]
Ah, didn't find that issue, thanks for clarifying. The use case is merely wanting pretty html output, but I understand the decision to focus of correct output rather than messing with formatting (it's a hard problem, orthogonal to Maud and worthy of a new crate). Thanks for the reply!

**Comment by xpe** [comment]
I read and understand the logic above, and I'd like to add some ideas to it to round it out.

The following process wouldn't be optimal: (a) export text; (b) parse; (c) format; (d) export text. Taking an end-to-end view, there are extra export and parse steps.

How to prevent those extra steps? By having the formatting be aware of the already-parsed data structure. Doing so involves some degree of coupling with Maud. There are many ways it could be done.
