### ISSUE TITLE
Feature request: Add build.rs support

### ISSUE THREAD

**Issue by mjptree** [lambda-fairy/maud#184]
# Summary
[summary]: #summary

Add support for build time parsing of templates.

# Motivation
[motivation]: #motivation

Having Html trees available at compile time allows for ultra low-latency in dynamically assembling web pages. However, it coerces template design and server development into the same responsiblity. In the worst case this requires source code modification of the server to change front-end logic. 

# Explanation
[explanation]: #explanation

As procedural macros are resolved at compile time, it does not allow to dynamically load separately defined source files to use as templates for interpolation. `build.rs` files however are automatically run before compilation and could serve to parse templates from a separate template location, e.g. `/templates` into maud-compatible Rust syntax.

## Example:
```
// build.rs

use maud::build;

fn main() {
    let template = build::from_template("./templates/nice_page.html");
    if let Err(_) = template.interpolate("src/main.rs", "nice_page") {
        println!("Interpolation failed!");
    }
}
````
### Alternative A: 
```
// src/main.rs

#![feature(proc_macro_hygiene)]

extern crate maud;
use maud::html;

fn main() {
    let name = "Lyra";`

    // If the template `nice_page` contains the variable `name` and is parsed correctly, the 
    // interpolation should be successful here
    let markup = html! { nice_page };
    println!("{}", markup.into_string());
}
```
### Alternative B: 
```
// src/main.rs

#![feature(proc_macro_hygiene)]

extern crate maud;
use maud::html;

fn main() {
    let name = "Lyra";`

    // Interpolates `name` into the template
    let markup = html_from_template! { nice_page, name };
    println!("{}", markup.into_string());
}
```

# Drawbacks
[drawbacks]: #drawbacks

A templating system that allows to write templates into external files that feel native to front-end developers could quickly degrade into defining its own DSL, similar to Tera or Handlebars. However, using a familiar templating syntax could also reduce change aversion of potential users.

# Alternatives
[alternatives]: #alternatives

- Currently, the approach to reach separation of front-end and back-end logic, could be solved in source code, by separating templates into separate `mod`s, so it they are still physically distinct, although both written in Rust syntax.

**Comment by lambda-fairy** [comment]
Does [Askama](https://crates.io/crates/askama) work for you?

**Comment by lambda-fairy** [comment]
I'm going to close this, as I'm pretty sure Askama would work for your use case. Feel free to reopen if you have follow-up questions :slightly_smiling_face:
