### ISSUE TITLE
web components / custom elements

### ISSUE THREAD

**Issue by bsl** [lambda-fairy/maud#185]
Hi, I'm looking at https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

Is there support in Maud for this kind of thing? I'm not familiar enough with Maud's internals to suggest a notation, but it seems like support for wacky element names might be possible.

**Comment by lambda-fairy** [comment]
Yes, Maud allows hyphens in element and attribute names, so you can use custom elements just fine. (Defining them is another matter -- a client-side library like [Dominator](https://github.com/Pauan/rust-dominator) would work better for that.)

I just realize that it's not mentioned in the docs. Perhaps you (or someone else) would like to fix that? :slightly_smiling_face:

**Comment by bsl** [comment]
Oh! Awesome. I never tried it. I thought Maud's macro knew about standard elements or something, but I can probably code `h666`. I'll try it later and if I think I understand, I'll try to make a PR that has some helpful docs. Maud can do a lot more than the docs let on. I often search through old issues for clues. Thanks for the quick answer, and for making Maud. (Oh -- FYI, my use case is Vue.js components, which I guess use this custom elements stuff.)

**Comment by lambda-fairy** [comment]
No worries! I am better at keeping docs up-to-date with PRs now, but many old gaps remain.
