### ISSUE TITLE
What should we do about the "should this be an `@if`" warning?

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/maud#189]
Currently, Maud emits a warning if you write an HTML element named `if`, `while`, `for`, `match`, or `let`:

```
warning: found keyword `if` - should this be a `@if`?
 --> $DIR/warn_on_keyword_names.rs:9:9
  |
9 |         if {}
  |         ^^

warning: 1 warning emitted
```

This is to catch the common issue where the user forgets to add a `@` before a keyword.

However, the proc macro diagnostics API (which supports this warning) is unstable. So for Maud to work on stable Rust, we need to decide what to do with the warning.

Do we:

1. Turn the warning into an error?
2. Silence the warning on stable Rust?

I am leaning toward (1) as it's unlikely that valid HTML contains an `<if>` tag.

**Comment by HeapUnderfl0w** [comment]
Until that diagnostics API is stable, i personally also would lean towards 1.

The only 'issue' that i could see cropping up as an edge case, is that someone tries to generate a template file with maud that is later consumed by some other tool (a handlebars template for example). But as i think that that is not a use-case maud was intended for, i think we can ignore that and just make it a hard-error.

**Comment by lambda-fairy** [comment]
Thanks for chiming in. Yeah, let's go with option (1).
