### ISSUE TITLE
Migrate to the third-party `quote!` macro

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/maud#191]
Currently, Maud uses the built-in `quote!` macro. This is unstable, though, so we'd like to switch to the third-party [`quote`](https://github.com/dtolnay/quote) crate instead. The `#![feature(proc_macro_quote)]` flag will be removed as part of this migration.

As noted in the [`quote` documentation](https://github.com/dtolnay/quote/blob/master/README.md#returning-tokens-to-the-compiler), the third-party macro returns `proc_macro2::TokenStream` instead of the built-in `proc_macro::TokenStream`. So we'll need to use e.g. `quote!( ... ).into()` or `TokenStream::from(quote!( ... ))` to convert it back. We will switch fully to `proc_macro2` in a future task; our goal here is to do the bare minimum needed to adopt the `quote` crate, not fix everything at once :wink:

**Comment by HeapUnderfl0w** [comment]
So ive taken a shot at moving stuff over to the 3rd party quote, and ive noticed that due to the avoidance of proc_macro2 a *lot* of coversions in both directions have to happen, as the functions pass proc_macro TokenStreams between them, while quote expects and emits proc_macro2  TokenStreams.

I will try to finish up anyway, but pushing up proc_macro2 in the list might help legibility imho.

**Comment by HeapUnderfl0w** [comment]
correction, after attempting to write all those conversions i ran into an issue. Often rustc needs some type-hinting for converting types properly as quote is so generic in what it can consume.

I see 2 options here:
- In one go, move the whole proc-macro portion to `proc_macro2`
- Include the proc_macro2 crate, but keep the function signatures as-is, and just use `proc_macro2` internally in the functions for type-hinting/conversions

**Comment by lambda-fairy** [comment]
Thanks for taking this up @HeapUnderfl0w! Yeah, I see how the conversions can be annoying.

My intention with sticking to `proc_macro` was to make this task as small as possible in scope. In particular I wasn't sure how to handle diagnostics with proc_macro2—[`Span::error`](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.error) and friends are not present in the `proc_macro2` version—and I'm worried that a solving that might make the PR much more complex. Maybe I'm overreacting, though, and we can just keep `proc_macro` in those specific places and use `proc_macro2` everywhere else?

Happy to hear what you think :slightly_smiling_face:

**Comment by HeapUnderfl0w** [comment]
If you are not opposed to adding `proc_macro2` as a dependency for that pr, i can see what i can do with keeping the error spans and so on faithful to the current state.

As a side node, i think `Span::error` and co. are not in `proc_macro2` yet because they are still unstable API.

**Comment by CreepySkeleton** [comment]
> Span::error and friends are not present in the proc_macro2 version

And this is exactly why I've put [`proc-macro-error`](https://crates.io/crates/proc-macro-error) together. This crate reimplements `proc_macro::Diagnostic` on top of `compile_error!` (error-reporting part only) in a way that works on stable charmingly in most cases and reasonably well in others. On nightly, it delegates to proper `proc_macro::Diagnostic`.

Examples of multi-token errors: [one](https://github.com/TeXitoi/structopt/blob/b1174e5c9c0001386d7c0ca5e106f606d955eed1/tests/ui/enum_flatten.stderr#L1) [two](https://github.com/TeXitoi/structopt/blob/b1174e5c9c0001386d7c0ca5e106f606d955eed1/tests/ui/opt_opt_nonpositional.stderr#L1)

@lambda-fairy Would you be open to such PR?

**Comment by lambda-fairy** [comment]
Thanks for the suggestion @CreepySkeleton!

I have created a separate issue: #196. Let's continue the discussion there.
