### ISSUE TITLE
Add a shim for the unstable diagnostics API

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/maud#196]
Maud uses the proc macro diagnostics API for friendly error messages. This API is nightly-only, though, so we'll need to fall back to `compile_error!` or `panic!` on a stable compiler.

There is a [`proc-macro-error`](https://crates.io/crates/proc-macro-error) library that provides this functionality. We should investigate whether it meets our needs.

As discussed on #189, the "should be an `@if`" warning should be changed to an error as well.

**Comment by lambda-fairy** [comment]
Two questions for @CreepySkeleton:

1. What's the reasoning behind basing the API on macros? Since it's a wrapper around the `proc_macro` diagnostics API, I would expect to match that closely.
2. Are you and @HeapUnderfl0w happy to work on your respective tasks in parallel? Depending on timing, one or both of you might need to rebase—probably not a big deal but I just want to point that out 🙂

I'll be happy to take a PR once these questions are resolved.

**Comment by CreepySkeleton** [comment]
> What's the reasoning behind basing the API on macros? Since it's a wrapper around the proc_macro diagnostics API, I would expect to match that closely.

Purely personal preference. All the maacros are build on top of `proc_macro_error::Diagnostic` which works great on its own, you can just use it directly if you like it that way.

> Are you and @HeapUnderfl0w happy to work on your respective tasks in parallel? Depending on timing, one or both of you might need to rebase—probably not a big deal but I just want to point that out 🙂

No problems on my side, I don't think the rebase would be very hard 🤷

**Comment by lambda-fairy** [comment]
Thanks for the info!

I slightly prefer the `Diagnostic` API, as (a) I find it more familiar and (b) it'll be easier to switch back to the `proc_macro` version when that stabilizes. But that preference is not very strong.

Also, it looks like some functionality is missing from the public `Diagnostic` API—there appears to be some special span handling that is only present in the macro version.

Overall, I'll be happy with a PR that takes either approach :smile:

**Comment by CreepySkeleton** [comment]
Here we go. This is _still_ sunday at my place so the deadline is technically met 🙄

**Comment by lambda-fairy** [comment]
Thanks @CreepySkeleton! I am very busy with work at the moment, so I won't be able to review until the end of the week. But I really appreciate the work you've put into this!
