### ISSUE TITLE
Improve error message for invalid attribute values

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/maud#208]
Currently, when the user types in:

```rust
input type="number" min=0 max=100;
```

or

```rust
script src="pinkie.js" defer=true;
```

or

```
.col-sm-2 {}
```

they get the error "expected string". This is technically correct but I think we can do better.

- For number literals (integer or float), suggest wrapping the number in quotes.
    - Alternatively, we can accept the number literal as-is, but I think that can be confusing because adding parentheses to the value can change the result. See https://github.com/lambda-fairy/maud/issues/208#issuecomment-798227760
- For boolean literals, suggest removing the `=true` bit altogether.

**Comment by CreepySkeleton** [comment]
> For example, 0x2a and 0.99999999999999999999999 will be parsed as 42 and 1.0 respectively.

Actually, while `Literal::*` methods do lose precision, `impl FromStr for TokenStream` [seems to be able](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=10272012d86885de4637462eee9d9a9e) to round-trip number literals loselessly. There rest is pretty easy.

**Comment by lambda-fairy** [comment]
Ah, that's interesting. I'm still against allowing that, though, as it means that factoring out a variable can change the result:

```rust
html! { 0x2a }  // "0x2a"

let ponk = 0x2a;
html! { (ponk) }  // "42"
```

**Comment by CreepySkeleton** [comment]
But `ponk` is not a literal, it's an identifier. It shouldn't be a subject to suggestions in the first place.

**Comment by lambda-fairy** [comment]
To clarify, I mean that so far it's been true that adding parentheses `()` to a literal doesn't change it:

```rust
html! { "ponk" }  // "ponk"
html! { ("ponk") }  // "ponk"
```

But allowing bare number literals will break this property:

```rust
html! { 0x2a }  // "0x2a"
html! { (0x2a) }  // "42"
```

**Comment by lambda-fairy** [comment]
#265 improves the error message for non-string literals in element bodies and attribute values.

It still leaves numbers in class/ID shorthand (`.col-sm-2`). I'll file a follow-up issue to address that.
