### ISSUE TITLE
Fails when numbers are provided in class names

### ISSUE THREAD

**Issue by mitchhentges** [lambda-fairy/maud#241]
[Bootstrap's grid system](https://getbootstrap.com/docs/4.0/layout/grid/#variable-width-content) involves classes with numbers, such as `col-sm-2`. This fails at compilation with the error: "expected string".

For example:
```
html! {
    .col-sm-2 {}
}
```

```
error: expected string
 --> file.rs:6:34
  |
n |     let markup = html! { .col-sm-2 {} };
  |                                  ^
```

**Comment by lambda-fairy** [comment]
Does this work?

```rust
html! {
    ."col-sm-2" {}
}
```

The confusing error message is covered by #208, but I just notice that the [docs](https://maud.lambda.xyz/elements-attributes.html) don't mention this at all... whoops :facepalm:
