### ISSUE TITLE
The example "rendering Markdown using pulldown-cmark and ammonia" does not compile

### ISSUE THREAD

**Issue by powerconnector** [lambda-fairy/maud#247]
The "rendering Markdown using pulldown-cmark and ammonia" example on https://maud.lambda.xyz/render-trait.html does not compile. I am not sure about the specific reason why it doesn't work but I guess ~~one would have to `write!` to the `buffer` instead of returning `PreEscaped(safe_html)`~~ the signature of the function of the  Render trait has changed?

I guess it should be something like

```rust
impl<T: AsRef<str>> Render for Markdown<T> {
    fn render(&self) -> Markup {
        // Generate raw HTML
        let mut unsafe_html = String::new();
        let parser = Parser::new(self.0.as_ref());
        html::push_html(&mut unsafe_html, parser);
        // Sanitize it with ammonia
        let safe_html = ammonia::clean(&unsafe_html);
        PreEscaped(safe_html)
    }
}
```

**Comment by lambda-fairy** [comment]
Thanks for reporting!

Yeah, that looks like a simple typo. I'll fix.
