### ISSUE TITLE
First and last elements?

### ISSUE THREAD

**Issue by chrisglass** [lambda-fairy/maud#275]
Hi, and thanks for the awesome framework!

I apologize if this isn't the right venue to ask questions (I'm happy to be shown where the right venue for this would be instead).

One of my current pages presents a table, and I would like to render the colour for the first and last rows of that table a different colour (technically, a different CSS class). How could I do this using Maud?

Conceptually:
```
html! {
  @for row in [Row; 18] {
    @if <the first row> {
       tr class="special" {}
    } @else {
       tr class="notspecial" {}
    }
  }
}
```

It feels like a case of me holding it wrong, but I would nonetheless very much appreciate a nudge in the right direction :)

**Comment by chrisglass** [comment]
Answering my own question and closing this: I was, indeed, holding it wrong.

My simple answer was to create a new type for the presentation that has a class attribute, and preprocess my table to pass a Vec of my new type to the macro. Works great!

Sorry for the noise :)

**Comment by lambda-fairy** [comment]
You can use [`.enumerate()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate):

```rust
html! {
  @for (i, row) in rows.iter().enumerate() {
    @if i == 0 || i == rows.len() - 1 {
       tr class="special" {}
    } @else {
       tr class="notspecial" {}
    }
  }
}
```

Also, if you're only changing presentation, not content, then it would be cleaner to use the CSS [`:first-child`](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child) / `:last-child` selectors instead.

**Comment by chrisglass** [comment]
Oh, that's much more elegant indeed. Thanks a lot of the hint!

Yes, I would use CSS for this exact example - but my actual use case is a little more complicated. The `.enumerate()` function is exactly what I needed however, thanks a lot.
