### ISSUE TITLE
Very slight breakage by Rust 2021 Edition

### ISSUE THREAD

**Issue by SorteKanin** [lambda-fairy/maud#308]
Rust 2021 has reserved the `prefix#identifier` syntax. This causes the following to fail to compile
```
use maud::html;

fn main() {
    let markup = html! {
        div#my-id {}
    };
}
```
because `div#my-id` uses the reserved syntax.

The easy fix is just to add a space between the tokens: `div #my-id`. Not very significant but [the examples on the website](https://maud.lambda.xyz/elements-attributes.html) should perhaps be updated with a note about Rust 2021.

**Comment by lambda-fairy** [comment]
Thanks!

Yeah, I have the changes for this locally. Just need to clean it up.

I'll assign myself in the meantime.

**Comment by lambda-fairy** [comment]
BTW, the docs on `main` mention some unreleased features (#283). So to avoid confusion, I'll hold off on deploying the docs changes until I cut a new release.
