### ISSUE TITLE
Cannot set attribute on <html> element

### ISSUE THREAD

**Issue by kthy** [lambda-fairy/maud#326]
Hi, thanks for the great work on this crate! Am I right in assuming there's no support for attributes on the `<html>` element?

It is customary in HTML5 to [always use a language attribute on the `<html>` element to declare the default language of the text in the page](https://www.w3.org/International/questions/qa-html-language-declarations). I can't see any apparent way to do this in Maud, since the `<html>` is implicit.

**Comment by kthy** [comment]
I just now realized I simply need to do

```rust
html! {
    (DOCTYPE)
    html class="no-js" lang="" {
        head {
            …
        }
        body {
            …
        }
    }
}
```

Closing as PEBKAC. Sorry about the noise.

**Comment by wjholden** [comment]
So FYI for any random person doing the same thing 4 years later...

Today I learned that you do not need to close your `<html>` and `<body>` tags in HTML5. So, if you open these tags in some [header partial](https://maud.lambda.xyz/partials.html), it will be OK that there is no matching curly brace in the footer.

For example,

```rust
fn example_header() -> Markup {
    html! {
        (DOCTYPE)
        html lang="en";
        head { title { "Hello world!" } }
        body;
    }
}

#[get("/example")]
fn example() -> Markup {
    html! {
        (example_header())
        p { "This HTML is valid." }
    }
}
```

generates

```html
<!DOCTYPE html><html lang="en"><head><title>Hello world!</title></head><body><p>This HTML is valid.</p>
```

which is valid HTML5 with no warnings according to the [W3C Validator[(https://validator.w3.org).
