### ISSUE TITLE
How to make an optional empty attribute?

### ISSUE THREAD

**Issue by Riateche** [lambda-fairy/maud#327]
I need something like this:
```
input type="radio" name="f" value="a" checked=(value == 'a');
input type="radio" name="f" value="b" checked=(value == 'b');
```
This doesn't work because it just generates `checked="true"` or `checked="false"`. I can work around it like this:
```
input type="radio" name="f" value="a" checked=[if value == 'a' { Some("") } else { None }];
```
It generates `checked=""` if the value matches and nothing otherwise, so it technically works, but it's inconvenient and it would be cleaner to generate an empty attribute.

It would be nice if `checked=[value == 'a']` was rendered to `checked` or nothing.

**Comment by lambda-fairy** [comment]
Hi @Riateche, sorry for the delay 😄

Does this work?

```rust
input type="radio" name="f" value="a" checked[value == 'a'];
```

i.e. remove the `=` from `checked`.

--------

On that note: I notice that the [optional attributes](https://maud.lambda.xyz/elements-attributes.html#optional-attributes-titlesomevalue) section is on a different page to the other [splices and toggles](https://maud.lambda.xyz/splices-toggles.html#toggles-foo). I see how that can be confusing. So I'm happy to accept a PR that moves them together.

**Comment by lambda-fairy** [comment]
> So I'm happy to accept a PR that moves them together.

#369
