### ISSUE TITLE
Axum integration does not work with v0.5

### ISSUE THREAD

**Issue by jquesada2016** [lambda-fairy/maud#339]
The current version of `maud` does not work with the latest version of `axum`.

This appears to be a version incompatibility.

**Comment by jquesada2016** [comment]
I was taking a look at this to create a pull request to fix it, but it seems like there's something else going on. The compiler is saying that the `IntoResponse` trait implemented by `maud` is different (`axum-core`) than the one used by `axum` directly, which doesn't make any sense. I'll report back as soon as I find something.

**Comment by jquesada2016** [comment]
Hello! You beat me to it! I was especially confused because the version in Cargo.toml on the main branch was `0.23`, which I was using, but when checking the sources, they didn't match at all! It wasn't until I tried linking directly to the git dependency that it worked. Good to move to use `axum-core`, which is pretty stable, vs `axum` directly.

**Comment by lambda-fairy** [comment]
No worries – thank the Axum maintainers for doing that 🙂

**Comment by yudai-nkt** [comment]
Hi @lambda-fairy. Thanks for making maud, I really like your compile-time approach!

> You can either [use a git dependency](https://stackoverflow.com/a/69317166/617159) or wait for me to cut a release.

Would you mind releasing a new version that includes this fix? I was fine with the git dependency until recently, but when it comes to publishing my binary crate to crates.io, the registry won't allow git dependency and causes me [this error](https://github.com/yudai-nkt/gh-form/runs/7801637276?check_suite_focus=true) saying "all dependencies must have a version specified when publishing."
