### ISSUE TITLE
Web frameworks documentation broken

### ISSUE THREAD

**Issue by litchipi** [lambda-fairy/maud#340]
On the section about web framworks integrations [here](https://maud.lambda.xyz/web-frameworks.html), the `actix_web` example does not work.

Versions used:
- rustc: `1.58.0 (02072b482 2022-01-11)`
- maud: `0.23.0` (using the proper feature)
- actix_web: `4.0.1`

Error got:
```
#[get("/")]
^^^^^^^^^^^ the trait `Responder` is not implemented for `PreEscaped<String>`
```

**Comment by lambda-fairy** [comment]
Hi there,

Actix Web 4.0 support was merged in #331, but it hasn't been released yet.

You can use a [git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) in the meantime.

LMK if you have further questions!
