### ISSUE TITLE
escape.rs symlink broken on Windows

### ISSUE THREAD

**Issue by lunabunn** [lambda-fairy/maud#343]
Current main is broken on Windows due to [maud_macros/src/escape.rs](https://github.com/lambda-fairy/maud/blob/main/maud_macros/src/escape.rs) being a symlink, [which is broken on Windows](https://github.com/rust-lang/cargo/issues/5664).

The obvious fix would be to copy-and-paste the contents over, but perhaps there's a better solution?

**Comment by lambda-fairy** [comment]
Oh, that's unfortunate.

I originally added that symlink to avoid duplicating the file. I thought it was an improvement over the previous approach, which was to publish a separate helper crate that was a dependency of both.

What do other libraries do instead?

**Comment by lunabunn** [comment]
> Oh, that's unfortunate.
> 
> I originally added that symlink to avoid duplicating the file. I thought it was an improvement over the previous approach, which was to publish a separate helper crate that was a dependency of both.
> 
> What do other libraries do instead?

Could we just have `escape.rs` live in `maud_macros`, and then reexport that from `maud`?

**Comment by lambda-fairy** [comment]
IIRC, proc macro crates can only export macros, not normal functions.

**Comment by Xe** [comment]
This is broken on NixOS too when building in the nix store.

**Comment by lambda-fairy** [comment]
Looks like the symlink approach has too many downsides. I'll just duplicate it then 😿
