### ISSUE TITLE
(minor) formatting in IntellIJ?

### ISSUE THREAD

**Issue by yatesco** [lambda-fairy/maud#349]
just a quick question - any tips on how to configure IntelliJ (CLion) so that it formats code inside the `html!` macro? Thanks!

**Comment by lambda-fairy** [comment]
Hi @yatesco!

Sorry for the late response.

Unfortunately I don't have an answer here, as I don't use JetBrains IDEs. But I think it's unlikely as Maud's syntax is entirely custom. You'd need a bespoke formatter plugin I believe.

LMK if you have any further questions!
