### ISSUE TITLE
Axum example not working

### ISSUE THREAD

**Issue by piccell** [lambda-fairy/maud#366]
Hi,

I copied/pasted the example for Axum integration with the following dependencies:
[dependencies]
axum = "0.6"
maud = { version = "*", features = ["axum"] }
tokio = { version = "1.0", features = ["full"] }

But I have the following compiling error:
the trait bound `fn() -> impl std::future::Future<Output = hello_world::{closure#0}::maud::PreEscaped<std::string::String>> {hello_world}: axum::handler::Handler<_, _, _>` is not satisfied
the trait `axum::handler::Handler<T, S, B2>` is implemented for `axum::handler::Layered<L, H, T, S, B, B2>`

Should I use a specific version ?

Best regards

**Comment by alleyshairu** [comment]
I believe that is because the version of maud on crates isn't updated to the latest commit which has axum 0.6 support. You can directly specify the git url to get the latest changes.

`maud = { git= "https://github.com/lambda-fairy/maud", features = ["axum"] }`
