### ISSUE TITLE
Error with attributes formatted like `abc-123`

### ISSUE THREAD

**Issue by spiffytech** [lambda-fairy/maud#384]
When an attribute has a hyphen followed by a number, Maud mistakes the attribute for an element body and will not compile it:

`div abc-123="";`

```
literal must be double-quoted: `"123"`
element body must be wrapped in braces

  = help: see https://github.com/lambda-fairy/maud/pull/137 for details
```

This prevents the use of the [HTMX response-targets extension](https://htmx.org/extensions/response-targets/#usage), which embeds HTTP status codes in element attributes.

**Comment by lambda-fairy** [comment]
Fixed in HEAD, thanks!
