### ISSUE TITLE
aggressive minification

### ISSUE THREAD

**Issue by FallBackITA27** [lambda-fairy/maud#397]
``` p {"values: "} ``` -> ```<p>values:</p>```

This is obviously an issue. Minifying code is fine, but against user input is painful to deal with.

**Comment by lambda-fairy** [comment]
Hi, would you like to give a minimal example?

Maud doesn't minify. So I'm not sure how you're seeing this behavior.

**Comment by zr40** [comment]
@FallBackITA27 If you're using the browser's inspector rather than 'view source', you're seeing the resulting DOM, not the input HTML. Insignificant whitespace is stripped by the browser's HTML parser before appearing in the DOM.

**Comment by FallBackITA27** [comment]
> Insignificant whitespace is stripped by the browser's HTML parser before appearing in the DOM.

Nope, it's made into text nodes which are visible to the user and you can actually interact, depending on the tag.

You can actually see this by logging child nodes on an indented element.

**Comment by FallBackITA27** [comment]
> Hi, would you like to give a minimal example?

```
fn build() {
    let x = maud::html {
        head { title { "test" }  };
        body {
            p { "Shroomstrat: " };
        };
    }.to_string();
    std::fs::write("./t.html", x.as_bytes()).unwrap();
}```

The result is as stated above, where the content of p, meaning that space, is removed.
I'm unsure if the example works, I just winged it

**Comment by zr40** [comment]
The example does not compile; there's no `maud::html` function. There is a `maud::html!` macro, but there is no `.to_string()` function on the `PreEscaped<String>` it returns.

Changing your example as follows:
```rust
    fn build() {
        let x = maud::html! {
            head { title { "test" }  };
            body {
                p { "Shroomstrat: " };
            };
        }
        .into_string();

        std::fs::write("./t.html", x).unwrap();
    }
```

This creates the following output file:
```html
<head><title>test</title></head><body><p>Shroomstrat: </p></body>
```
Note that the space is not removed.

**Comment by FallBackITA27** [comment]
Huh. I'll look into it on my own, absolutely 0 idea on why the output isn't the same.
