### ISSUE TITLE
Shouldn't `escape_to_string` escape `'` characters?

### ISSUE THREAD

**Issue by benwr** [lambda-fairy/maud#413]
I note that `escape_to_string` doesn't currently escape `'` characters. IIUC these can be used to delimit attributes, so I'd have thought you'd want to escape them. Is that wrong?

**Comment by benwr** [comment]
Ah, maybe this doesn't matter because you always generate double-quoted attributes. Sorry if that's the case! Just doing a drive-by low-effort audit while trying to evaluate templating options.

**Comment by lambda-fairy** [comment]
Indeed, we only emit double-quoted attributes so it doesn't matter.

Technically we don't have to escape `>` either, but that might offend the XML folks.
