### ISSUE TITLE
Add a lint plugin for detecting common anti-patterns

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/maud#66]
We can lint these things:

* [x] Use `maud::DOCTYPE` instead of `PreEscaped("<!DOCTYPE html>")`

* [ ] Rather than writing `output.push_str(&html! { ... }.into_string())`, just implement the [`render`](https://docs.rs/maud/0.14.0/maud/trait.Render.html#method.render) method instead

* [ ] Use `format_args!` (or list the values individually) instead of `format!`

The following lints inspect the structure of the template itself. It's not clear yet how they can be implemented under the current design. We'll probably need to do some refactoring before these can work.

* [ ] Use `.foo` instead of `class="foo"`, and `#foo` instead of `id="foo"`

    + [ ] Use `.foo[bar]` instead of `class=@if bar { "foo" }`

* [ ] Warn against [`a target="..."` without `rel="noopener"`](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)

* [ ] Warn against dynamic data in CSS and JS contexts, e.g. `script { "var name = '" (user.name) "'" }`

* [ ] Warn about non-standard elements and attributes

Further suggestions welcome!

**Comment by ernestas-poskus** [comment]
thus elements that contains empty tags like id="" or class="" could be removed to minimize html size

**Comment by lfairy** [comment]
@ernestas-poskus that can be extended to other attributes like `style` and `rel` as well

**Comment by ernestas-poskus** [comment]
> that can be extended to other attributes like style and rel as well

sure, all empty tags could be removed

**Comment by lfairy** [comment]
> sure, all empty tags could be removed

Not all of them. `<script>` tags are almost always empty, for example. Empty tags can also be used as hooks for scripts and styling. And on an `<img>` tag, an empty `alt` attribute and a missing `alt` attribute [have different meanings][1].

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Attributes

**Comment by lfairy** [comment]
I have started improving the lint plugin on the [better-lints](https://github.com/lfairy/maud/compare/better-lints) branch. When I'm done, the proc macro will use compile-time "markers" to communicate the structure of the original template to the lint plugin.

**Comment by lfairy** [comment]
#127 🎉

**Comment by lambda-fairy** [comment]
This issue has become a bit of a laundry list of suggestions. It's unclear how half of these can be implemented on stable (given that third-party lints are so far away) and the tractable stuff has already been split out (e.g. #181). So I'm going to close this as wontfix.
